### PR TITLE
fixes #135 check map.source before pre-pending dirname

### LINKED ISSUE #135: [Bug] Incorrect prepending of map.sources e.g. dist/dist/dist/source.scss
https://github.com/egoist/rollup-plugin-postcss/blob/master/src/index.js#L151

In watch mode and extract mode, this map.sources keeps on appending when map files don't get regenerated, causing prepending dirname in this case dist/dist/dist/sources.scss and keeps repeating appending for every watch iteration.

### PR DESCRIPTION
**Pull request by van-nguyen**
Just need to check if dirname is there already before pre-pending to source path

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -148,8 +148,9 @@ export default (options = {}) => {
           const map = res.map || null
           if (map) {
             map.file = filepath
+            const dirname = path.dirname(opts.file)
             map.sources = map.sources.map(source =>
-              humanlizePath(path.join(path.dirname(opts.file), source))
+              source.substr(0, dirname.length) === dirname ? source : humanlizePath(path.join(path.dirname(opts.file), source))
```
Comment (lmihaidaniel) [inline src/index.js]: Minor: we should use the defined const `dirname` instead.

Comment (van-nguyen) [reply src/index.js]: Good pickup, I have resolved for any other places that can make use of the const also.
